### ISSUE TITLE
Failed to install dependencies from the pack

### ISSUE THREAD

**Issue by mrdrprofuroboros** [bentoml/comfy-pack#16]
here's the verbose log:

```bash
Installing dependencies from /tmp/tmph99l688k/.cpack/requirements.txt
Traceback (most recent call last):
  File "/home/ubuntu/venv/bin/comfy-pack", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/venv/lib/python3.10/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/venv/lib/python3.10/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/comfy_pack/cli.py", line 266, in unpack_cmd
    install(cpack, dir, verbose=verbose, all_models=include_disabled_models)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/comfy_pack/package.py", line 382, in install
    install_dependencies(snapshot, str(req_txt_file), workspace, verbose=verbose)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/comfy_pack/package.py", line 156, in install_dependencies
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['uv', 'pip', 'install', '-p', 'ComfyUI/.venv/bin/python', '-r', '/tmp/tmph99l688k/.cpack/requirements.txt', '--no-deps']' returned non-zero exit status 1.
```

comfy-cli==1.3.1
comfy-pack==0.2.1
uv==0.5.13

I unpacked the package and tried to install requirements.txt manually with pip and it failed since pip couldn't resolve flash-attn dependency on torch

I did install torch myself
```bash
pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu121
```

but it didn't help, still same flash-attn failing to resolve it though it is even installed
so i commented out flash-attn from requirements, installed them
then uncommented it back and it went smooth O_o

OK, now i presumably have the env installed to ComfyUI/.venv, let's run unpck again: same error as above (exited 1)
Let's do uv install manually
```bash
uv pip install -p ComfyUI/.venv/bin/python -r requirements.txt --no-deps

Using Python 3.10.16 environment at: ComfyUI/.venv
  × No solution found when resolving dependencies:
  ╰─▶ Because there is no version of torch==2.5.1+cu121 and you require torch==2.5.1+cu121, we can
      conclude that your requirements are unsatisfiable.
```

aha, same torch related thing, gotcha
```bash
uv pip install -p ComfyUI/.venv/bin/python -r requirements.txt --no-deps  --extra-index-url https://download.pytorch.org/whl/cu121

Using Python 3.10.16 environment at: ComfyUI/.venv
  × No solution found when resolving dependencies:
  ╰─▶ Because there is no version of certifi==2024.12.14 and you require certifi==2024.12.14, we
      can conclude that your requirements are unsatisfiable.

      hint: `certifi` was found on https://download.pytorch.org/whl/cu121, but not at the
      requested version (certifi==2024.12.14). A compatible version may be available on a
      subsequent index (e.g., https://pypi.org/simple). By default, uv will only consider
      versions that are published on the first index that contains a given package, to avoid
      dependency confusion attacks. If all indexes are equally trusted, use `--index-strategy
      unsafe-best-match` to consider all versions from all indexes, regardless of the order in
      which they were defined.
```

OK, let's try
```
uv pip install -p ComfyUI/.venv/bin/python -r requirements.txt --no-deps  --extra-index-url https://download.pytorch.org/whl/cu121 --index-strategy unsafe-best-match

Using Python 3.10.16 environment at: ComfyUI/.venv
⠸ asgiref==3.8.1                                                                                    thread 'uv-resolver' panicked at crates/uv-resolver/src/resolver/environment.rs:568:9:
resolver must be in universal mode for forking
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: The channel closed unexpectedly
```

ahahah here we are

So even though I now have the fully installed environment (with just manual pip) I can't unpack the rest of the workspace (custom nodes and models) because comfy-unpack expects uv to succeed.
- being able to skip env installation would be great

But moving on :)
I went down the rabbit hole and commented out 
https://github.com/bentoml/comfy-pack/blob/06173cea47112adc9597a496e60b334db19bc4d2/src/comfy_pack/package.py#L382

and got
```bash
Installing custom nodes
Traceback (most recent call last):
  File "/home/ubuntu/venv/bin/comfy-pack", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/venv/lib/python3.10/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/venv/lib/python3.10/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/comfy_pack/cli.py", line 266, in unpack_cmd
    install(cpack, dir, verbose=verbose, all_models=include_disabled_models)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/comfy_pack/package.py", line 397, in install
    install_custom_modules(snapshot, workspace, verbose=verbose)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/comfy_pack/package.py", line 76, in install_custom_modules
    _clone_commit(url, commit_hash, module_dir, verbose=verbose)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/comfy_pack/package.py", line 20, in _clone_commit
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'clone', '--recurse-submodules', '--filter=blob:none', '', PosixPath('ComfyUI/custom_nodes')]' returned non-zero exit status 128.
```

Looking at my snapshot.json I discover
```json
...
  "custom_nodes": [
    {
      "url": "",
      "commit_hash": "",
      "disabled": false
    },
    {
      "url": "",
      "commit_hash": "",
      "disabled": false
    },
    ...
...
```

oh, this is something that went completely wrong with the export (I did it via UI), don't have that environment anymore unfortunately

So 3 things here for you to share:
- uv might be nice fast and fancy, but good old pip might be more robust
- making cli opting to skip dependencies/custom_nodes/models might be a good idea
- something went completely wrong with the export, I can't debug it already, but I might be not alone

**Comment by bojiang** [comment]
Love your story, pretty informative and helpful.

**Comment by bojiang** [comment]
For uv issue, @mrdrprofuroboros  would you mind sharing us the requirements.txt file? uv is important to reuse Python packages.

cc @frostming

**Comment by mrdrprofuroboros** [comment]
[requirements.txt](https://github.com/user-attachments/files/18265372/requirements.txt)
here you go

**Comment by bojiang** [comment]
https://github.com/bentoml/comfy-pack/pull/21
